#!/usr/bin/groovy

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

	environment {
		PYTHONPATH = "${WORKSPACE}/section_4/code/cd_pipeline"
		IMAGE_NAME = "hands-on-jenkins/myapp:${BUILD_NUMBER}"
	}

    stages {

		stage("Test - Unit tests") {
			steps { runUnittests() }
		}

        stage("Build") {
            steps { buildApp() }
		}

        stage("Deploy - Dev") {
            steps { deploy('dev') }
		}

		stage("Approve1") {
            steps { approve() }
		}

        stage("Deploy - Stage") {
            steps { deploy('stage') }
		}

        stage("Approve") {
            steps { approve() }
		}

        stage("Deploy - Live") {
            steps { deploy('live') }
		}
	}
}


// steps
def buildApp() {
	dir ('section_4/code/cd_pipeline' ) {
		def appImage = docker.build("${IMAGE_NAME}")
	}
}


def deploy(environment) {

	def containerName = ''
	def port = ''

	if ("${environment}" == 'dev') {
		containerName = "app_dev"
		port = "8888"
	} 
	else if ("${environment}" == 'stage') {
		containerName = "app_stage"
		port = "88"
	}
	else if ("${environment}" == 'live') {
		containerName = "app_live"
		port = "80"
	}
	else {
		println "Environment not valid"
		System.exit(0)
	}

	sh "docker ps -f name=${containerName} -q | xargs --no-run-if-empty docker stop"
	sh "docker ps -a -f name=${containerName} -q | xargs -r docker rm"
	sh "docker run -d -p ${port}:5000 --name ${containerName} ${IMAGE_NAME}"
}


def approve() {

	timeout(time:1, unit:'DAYS') {
		input('Do you want to deploy to live?')
	}

}

def runUnittests() {
	withDockerContainer(image: "python:3.6-alpine") {
		sh "docker image ls"
		sh "pip3 install --no-cache-dir -r ./section_4/code/cd_pipeline/requirements.txt"
		sh "python3 section_4/code/cd_pipeline/tests/test_flask_app.py"
	}
}
